apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-psql-pv
spec:
  capacity:
    storage: 5Gi
  accessModes: 
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /var/lib/gitea/psql-data